code_ride/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("pages.urls")),
    path("", include("posts.urls")),
]

pages/urls.py
from django.urls import path
from .views import HomePageView, ThisPageView, GamePageView, MeteoPageView, ScrapingPageView, RisPageView, ChatbotPageView, SqlitePageView, ImgslcPageView, SkillsPageView
from django.conf.urls.static import static


urlpatterns = [
		path("", HomePageView.as_view(), name="home"),
		path("skills/", SkillsPageView.as_view(), name="skills"),
		path("this/", ThisPageView.as_view(), name="this"),
		path("game/", GamePageView.as_view(), name="game"),
		path("meteo/", MeteoPageView.as_view(), name="meteo"),
		path("imgslc/", ImgslcPageView.as_view(), name="imgslc"),
		path("scraping/", ScrapingPageView.as_view(), name="scraping"),
		path("sqlite/", SqlitePageView.as_view(), name="sqlite"),
		path("ris/", RisPageView.as_view(), name="ris"),
		path("chatbot/", ChatbotPageView.as_view(), name="chatbot"),
		]

posts/urls.py
from django.urls import path
from .views import NewsPageView

urlpatterns = [
		path("news/", NewsPageView.as_view(), name="news"),
]

pages/models.py
from django.db import models

# Create your models here.

posts/models.py
from django.db import models

from django.urls import reverse

class Post(models.Model):
	title = models.CharField(max_length=200)
	author = models.ForeignKey("auth.User", on_delete=models.CASCADE,)
	body = models.TextField()
	created_at = models.DateTimeField(auto_now_add=True)
	
	def __str__(self):
		return self.title

	def get_absolute_url(self):
		return reverse("post_detail", kwargs={"pk": self.pk})

pages/views.py
from django.views.generic import TemplateView

class HomePageView(TemplateView):
	template_name = "home.html"

class ThisPageView(TemplateView):
	template_name = "this_site.html"

class GamePageView(TemplateView):
	template_name = "game.html"

class MeteoPageView(TemplateView):
	template_name = "meteo.html"

class ScrapingPageView(TemplateView):
	template_name = "scraping.html"

class RisPageView(TemplateView):
	template_name = "ris.html"

class ChatbotPageView(TemplateView):
	template_name = "chatbot.html"

class SqlitePageView(TemplateView):
	template_name = "sqlite.html"

class ImgslcPageView(TemplateView):
	template_name = "imgslc.html"

class SkillsPageView(TemplateView):
	template_name = "skills.html"

posts/views.py
from django.views.generic import ListView
from .models import Post

class NewsPageView(ListView):
	model = Post
	template_name = "news.html"
	queryset = Post.objects.all().order_by('-created_at')

templates/base.html
<!-- templates/base.html -->
{% load static %}
<!doctype html>
<!-- templates/base.html -->
<html lang="en">
  <head>
	  <meta charset="utf-8">
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
	  <title>MyCodeRide</title>
		<link rel="preconnect" href="https://fonts.googleapis.com">
		<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
		<link href="https://fonts.googleapis.com/css2?family=Corben&display=swap" rel="stylesheet">
	  <link rel="stylesheet" href="{% static 'css/base.css' %}">
	  <link rel="icon" href="{% static 'favicon.ico' %}" type="image/x-icon">
  </head>
	  <body>
		<header>
			<h1 class="logo">
			  my_code_ride.*
			  <span class="camel-icon"></span>
			</h1>
				<nav class="navigation_menu">
					<a href="{% url 'home' %}">home</a>
					<a href="{% url 'skills' %}">skills</a>
					<a href="{% url 'this' %}">thissite</a>
					<a href="{% url 'game' %}">game</a>
					<a href="{% url 'meteo' %}">meteo</a>
					<a href="{% url 'scraping' %}">scraping</a>
					<a href="{% url 'imgslc' %}">img_slc</a>	
					<a href="{% url 'sqlite' %}">sqlite</a>
					<a href="{% url 'ris' %}">ris</a>
					<a href="{% url 'chatbot' %}">chatbot</a>
					<a href="{% url 'news' %}">news</a>
				</nav>
		</header>
		<div>
			{% block content%}
			{% endblock content %}
		</div>
		<footer>
		    <p>
		        <script>
		            now = new Date();
		            year = now.getFullYear();
		            document.write("Copyright © " + year + " My Code Ride/coderide.eu");
		        </script>
		    </p>
		</footer>
	  </body>
</html>

templates/chatbot.html
{% extends "base.html" %}
{% load static %}
<!doctype html>
<!-- templates/ris.html -->
  <head>
	<meta charset="utf-8">
  </head>  	

	{% block content %}
	  <header>
	  	<h1 class="main">chatbot</h1>
	  </header>
	  <article>
	  	<header>
	  		<h2>Conversation Generator (Chatbot)</h2>
	  	</header>
	  	<nav class="basic">
	  		<a href="https://github.com/Tomas4python/chatbot.git" target="_blank" rel="noopener noreferrer">View code on Github</a>
	  	</nav>
	  	<section>
  			<p>The main objective of this project was to create a functional and interactive chatbot capable of generating coherent and contextually appropriate responses. The project involves both the technical aspects of machine learning model training and the practical aspects of GUI application development.</p>
	  	</section>
	  	<section>
	  		<header>
	  			<h3>About the Model</h3>
	  		</header>
  			<p>At the heart of the project is a sequence-to-sequence bidirectional encoder-decoder model built using Keras. This model is designed to generate conversations by encoding the input text and decoding it to produce a response. The encoder processes the input sequence and converts it into a context vector, which is then fed into the decoder to generate the output sequence. Two different response generation methods are implemented: argmax, which selects the most likely next word, and beam search, which considers multiple possible sequences to find the most probable one.</p>
  			<p>Data preprocessing is a critical part of the model development process. This involves cleaning and preparing the dataset, which consists of dialogue pairs, to ensure the model can learn effectively. The model is trained on this preprocessed data to optimize its ability to generate coherent responses. Once trained, the model is integrated into a real-time chatbot application.</p>
  			<p>The development paper included in the GitHub repository provides an extensive overview of the project, detailing the steps from data preprocessing to model development and the implementation of the chatbot application. This project aims to showcase the integration of advanced machine learning techniques with practical application development.</p>
  			<p>Below I’ve included several screenshots of Chatbot App.</p>
				<div class="carousel_container">  
				    <div class="carousel_slide carousel2 active">
				        <a href="{% static 'images/16_chatbot_1.jpg' %}" target="_blank">
				            <img src="{% static 'images/16_chatbot_1_s.jpg' %}" alt="Chatbot screenshot No.1">
				        </a>
				        <figcaption>Chatbot screenshot No.1.</figcaption>
				    </div>
				    <div class="carousel_slide carousel2">
				        <a href="{% static 'images/17_chatbot_2.jpg' %}" target="_blank">
				            <img src="{% static 'images/17_chatbot_2_s.jpg' %}" alt="Chatbot screenshot No.2">
				        </a>
				        <figcaption>Chatbot screenshot No.2.</figcaption>
				    </div>
				    <div class="carousel_slide carousel2">
				        <a href="{% static 'images/18_chatbot_3.jpg' %}" target="_blank">
				            <img src="{% static 'images/18_chatbot_3_s.jpg' %}" alt="Chatbot screenshot No.3">
				        </a>
				        <figcaption>Chatbot screenshot No.3.</figcaption>
				    </div>
				    <nav class="navigation_menu">
				        <button class="carousel_button" id="prevBtn2">prev</button>
				        <button class="carousel_button" id="nextBtn2">next</button>
				    </nav>
				</div>
	  	</section>
	  	<section>
	  		<header>
	  			<h3>Chatbot Application</h3>
	  		</header>
  			<p>The application itself, while a smaller part of the project, is crucial for demonstrating the model's capabilities. It features a customtkinter-based GUI with a conversation display field, an input field, and two fields for sample inputs. Users can enter a message and receive a response from the chatbot, or use pre-prepared text samples for quick testing. The intuitive design allows for easy interaction, and the 'Random' button adds convenience by generating random sample inputs. Check out the video demonstrating the chatbot in action:</p>
	  	  <video controls>
  				<source src="{% static '/videos/chatbot.mp4' %}" type="video/mp4">
  				<p>Your browser does not support HTML5 video.</p>
  			</video>
	  	</section>
	  </article>
	<script src="{% static 'javascript/buttons.js' %}"></script>
	{% endblock content %}

templates/game.html
{% extends "base.html" %}
{% load static %}
<!doctype html>
<!-- templates/game.html -->
  <head>
	<meta charset="utf-8">
  </head>  	

	{% block content %}
	  <header>
	  	<h1 class="main">game</h1>
	  </header>
	  <article>
	  	<header>
	  		<h2>ARTILLERY WAR, 21st Century, Eastern Font, Europe</h2>
	  	</header>
	  	<nav class="basic">
	  		<a href="https://github.com/Tomas4python/artillery_war.git" target="_blank" rel="noopener noreferrer">View code on Github</a>
	  	</nav>
	  	<section>
	  		<header>
	  			<h3>Introduction</h3>
	  		</header>
				<p>Shortly after diving into the world of Python through "PYTHON CRASH COURSE, 2ND EDITION" by Eric Matthes, I felt inspired to embark on the journey of game development. What began as an adventure with the `pygame` module soon evolved into a more comprehensive learning experience, leading me to explore the capabilities of the GUI library `tkinter`.</p>
	  		  <img src="{% static '/images/01_welcome.jpg' %}" alt="Welcome screen of the game">
			    <figcaption>Welcome to ARTILLERY WAR</figcaption>
	  	</section>
	  	<section>
	  		<header>
	  			<h3>Development Odyssey</h3>
	  		</header>
  			<p>In my first weeks of game coding, I aimed for a solid structure. However, as the game evolved into a complex and sophisticated endeavor, I found myself grappling with intricate code — not exactly spaghetti, but certainly more tangled than I would have preferred. As I delved into other app development projects, the value of a clear, cohesive structure became evident. This insight drove me to revisit and largely reengineer the game.</p>
  			<p>Switching the game's main engine to `tkinter` and `customtkinter` allowed me to achieve more homogeneous code, even if it meant sacrificing some canvas smoothness. This choice was driven by my keen interest in mastering the `tkinter` GUI.</p>
        <p>Throughout this process, I deepened my understanding of numerous core libraries, including but not limited to: `tkinter`, `customtkinter`, `PIL`, `os`, `pygame`, `math`, and `random`. Before this, Object-Oriented Programming (OOP) seemed abstract and elusive. Developing ARTILLERY WAR paved my way to a more profound grasp of OOP concepts, from referencing instances and understanding scopes to explore inheritance and function nesting.</p>
        <p>Midway, Chat GPT 4.0 came onboard, acting as an invaluable coding companion and a robust learning tool.</p>
	  	</section>
	  	<section>
	  		<header>
	  			<h3>Game Overview</h3>
	  		</header>
  			<p>ARTILLERY WAR doesn't focus on swift movements; it's an analytical challenge. It's a turn-based strategy where players input results derived from straightforward arithmetic operations—be it azimuth, elevation, wind speed, distance, or direction. With a plethora of calculations to make, it promises to be an intense mental workout.</p>
	  		<header>
	  			<h4>Features & Architecture:</h4>
	  		</header>
  			<ul class="no-indent">
  				<li><span class="itallic_bold_text"> Game Engine:</span> Rooted in `tkinter` and `customtkinter`.</li>
  				<li><span class="itallic_bold_text">Interactive Windows:</span> Four full-screen program windows, each serving unique gameplay interaction, easily navigable via keyboard commands and mouse.</li>
  				<li><span class="itallic_bold_text">Turn-Based Strategy:</span> Tests players on arithmetical calculations to plan their next move.</li>
  				<li><span class="itallic_bold_text">Modular & OOP Structure:</span> Including key modules like `game_loop.py` (game's main loop), `map.py` (battlefield visuals), `radar.py` (tracking & targeting), and many more.</li>
  				<li><span class="itallic_bold_text">Documents:</span> `about.txt` & `rules.txt` provide detailed game insights.</li>
  			</ul>
			<div class="carousel_container">  
			    <div class="carousel_slide carousel1 active">
			        <a href="{% static '/images/02_menu.jpg' %}" target="_blank">
			            <img src="{% static '/images/02_menu_s.jpg' %}" alt="Main menu screenshot">
			        </a>
			        <figcaption>Main Menu Interface</figcaption>
			    </div>
			    <div class="carousel_slide carousel1">
			        <a href="{% static '/images/03_radar.jpg' %}" target="_blank">
			            <img src="{% static '/images/03_radar_s.jpg' %}" alt="Radar view screenshot">
			        </a>
			        <figcaption>Radar View in Action</figcaption>
			    </div>
			    <div class="carousel_slide carousel1">
			        <a href="{% static '/images/04_drone.jpg' %}" target="_blank">
			            <img src="{% static '/images/04_drone_s.jpg' %}" alt="Drone view screenshot">
			        </a>
			        <figcaption>Bird's Eye View with the Drone</figcaption>
			    </div>
			    <div class="carousel_slide carousel1">
			        <a href="{% static '/images/05_console.jpg' %}" target="_blank">
			            <img src="{% static '/images/05_console_s.jpg' %}" alt="Console view screenshot">
			        </a>
			        <figcaption>Commanders console</figcaption>
			    </div>
			    <div class="carousel_slide carousel1">
			        <a href="{% static '/images/06_results.jpg' %}" target="_blank">
			            <img src="{% static '/images/06_results_s.jpg' %}" alt="Statistics view screenshot">
			        </a>
			        <figcaption>War statistics</figcaption>
			    </div>
			    <nav class="navigation_menu">
			        <button class="carousel_button" id="prevBtn">prev</button>
			        <button class="carousel_button" id="nextBtn">next</button>
			    </nav>
			</div>
  	</section>
	  	<section>
	  		<header>
	  			<h3>Download the Game</h3>
	  		</header>
				<p class="download_paragraph">
			   You can download the 114 MB ZIP file containing the executable version of the game, which is compatible with Windows 10-11, by clicking the 'download' button on the right. Additionally, the game's full source code can be accessed from the GitHub repository via the link provided above. I recommend reviewing the game requirements provided in the "about.txt" file. As with real-life soldiers preparing for war, it's essential to familiarize yourself with and practice the game to effectively engage in combat. Approach the game with patience, caution, and strategic thinking.
			  <button id="downloadButton" class="carousel_button">download</button>
				</p>
     	</section>
	  	<section>
	  		<header>
	  			<h3>Future & Forward</h3>
	  		</header>
  			<p>While I'm proud of what I've achieved, I'm aware of the journey ahead. I've recognized areas of improvement, and a third iteration should be on the horizon to further optimize the game. As I move forward, my focus will shift towards advanced OOP, rigorous testing, and refining code architecture.</p>
	  	</section>
	  	<section>
	  		<header>
	  			<h4>Discover More:</h4>
	  		</header>
  			<p>Dive into the immersive world of ARTILLERY WAR by watching this game video:</p>
  			<video controls>
  				<source src="{% static '/videos/artillery.mp4' %}" type="video/mp4">
  				<p>Your browser does not support HTML5 video.</p>
  			</video>
	  	</section>
	  </article>
	<script src="{% static 'javascript/buttons.js' %}"></script>
	{% endblock content %}

templates/home.html
{% extends "base.html" %}
{% load static %}
<!doctype html>
<!-- templates/home.html -->
  <head>
	<meta charset="utf-8">
	<link rel="stylesheet" href="{% static 'css/base.css' %}">
  </head>  	

	{% block content %}
	  <header>
	  	<h1 class="main">about</h1>
	  </header>
	  <article>
	  	<header>
	  		<h2>Welcome to My Learning Journey</h2>
	  	</header>
	  	<section>
  			<p>Welcome to the digital representation of my coding voyage. As you explore this site, you'll see the results of my extensive efforts in mastering Python, Tkinter, Django, HTML, CSS, JavaScript, SQL, and numerous Python libraries, including advanced machine learning techniques with Scikit-Learn, deep learning frameworks such as TensorFlow, PyTorch and Keras, data manipulation and analysis with Pandas and NumPy, data visualization with Matplotlib and Seaborn, and web scraping with BeautifulSoup and Selenium, all of which I have delved into during my Code Academy AI course.</p>
	  	</section>
	  	<section>
	  		<header>
	  			<h3>Showcasing Progress</h3>
	  		</header>
  			<p>This site features eight distinct applications, each demonstrating my growing proficiency in coding and the diverse skillset I've developed. These applications are more than just projects; they are milestones that reflect my dedication, perseverance, and passion for programming.</p>
  	</section>
	  	<section>
	  		<header>
	  			<h3>Continuous Learning</h3>
	  		</header>
  			<p>My approach to learning extends beyond formal education. I have completed the comprehensive Code Academy AI course, which significantly deepened my understanding of Python and artificial intelligence. In addition to this, I actively use alternative learning platforms such as Udemy, W3Schools, and Kaggle. Books also play a crucial role in my education, providing a structured foundation and allowing for easy reference and in-depth study.</p>
	        <img src="{% static 'images/12_home.jpg' %}" alt="Photo of stack of books">
	        <figcaption>Captured above: A stack of treasured books that have been instrumental in my learning process.</figcaption>
	  	</section>
	  	<section>
	  		<header>
	  			<h3>Gratitude and Acknowledgments</h3>
	  		</header>
  			<p>I owe a great deal of my progress to the incredible resources available online. From free tutorials and videos to paid courses and articles, the collective knowledge shared by countless educators and experts has been invaluable. I extend my heartfelt thanks to all who contribute to these resources, as their generosity and dedication have profoundly impacted my learning journey.</p>
	  	</section>
	  </article>
	{% endblock content %}

templates/imgslc.html
{% extends "base.html" %}
{% load static %}
<!doctype html>
<!-- templates/ris.html -->
  <head>
	<meta charset="utf-8">
  </head>  	

	{% block content %}
	  <header>
	  	<h1 class="main">img_slc</h1>
	  </header>
	  <article>
	  	<header>
	  		<h2>Image Processing Application</h2>
	  	</header>
	  	<nav class="basic">
	  		<a href="https://github.com/Tomas4python/image_slicing.git" target="_blank" rel="noopener noreferrer">View code on Github</a>
	  	</nav>
	  	<section>
  			<p>This Image Processing Application is designed as an educational project to explore and learn Python programming, with a particular focus on leveraging the NumPy library. The application processes images stored in a designated 'images' directory, supporting formats such as .jpg, .jpeg, .png, and .bmp.</p>
	  	</section>
	  	<section>
	  		<header>
	  			<h3>About the Application</h3>
	  		</header>
  			<p>The core functionality involves applying five distinct processing techniques to each image, showcasing the versatility and power of NumPy arrays in image manipulation. These processed images are then displayed in a simple user-friendly GUI built using Tkinter, offering a straightforward and interactive way to view the results. The application's architecture is deliberately structured to facilitate easy expansion, allowing for the addition of more processing methods without significant restructuring.</p>
  			<p>The basic features of the application include vertical and horizontal slicing of images into 20-200 slices using NumPy, image rotation, and image concatenation using vstack and hstack. Additional features include color filters that convert RGB images to grayscale, red, green, or blue, and a blur filter that applies a custom kernel to blur images. The application also handles RGBA images by removing the alpha channel to ensure compatibility with formats like JPEG. For testing, NumPy-based sample tests are included to validate image processing functions.</p>
  			<p>Below I’ve included several screenshots of Application.</p>
				<div class="carousel_container">  
				    <div class="carousel_slide carousel2 active">
				        <a href="{% static 'images/22_imgslc_1.jpg' %}" target="_blank">
				            <img src="{% static 'images/22_imgslc_1_s.jpg' %}" alt="Image Processing Application screenshot No.1">
				        </a>
				        <figcaption>Image Processing Application screenshot No.1.</figcaption>
				    </div>
				    <div class="carousel_slide carousel2">
				        <a href="{% static 'images/23_imgslc_2.jpg' %}" target="_blank">
				            <img src="{% static 'images/23_imgslc_2_s.jpg' %}" alt="Image Processing Application screenshot No.2">
				        </a>
				        <figcaption>Image Processing Application screenshot No.2.</figcaption>
				    </div>
				    <div class="carousel_slide carousel2">
				        <a href="{% static 'images/24_imgslc_3.jpg' %}" target="_blank">
				            <img src="{% static 'images/24_imgslc_3_s.jpg' %}" alt="Image Processing Application screenshot No.3">
				        </a>
				        <figcaption>Image Processing Application screenshot No.3.</figcaption>
				    </div>
				    <nav class="navigation_menu">
				        <button class="carousel_button" id="prevBtn2">prev</button>
				        <button class="carousel_button" id="nextBtn2">next</button>
				    </nav>
				</div>
	  	</section>
	  	<section>
  			<p>This project was also oriented towards developing the application while adhering to a proper development structure. The project includes command line arguments, a comprehensive README.md, and a requirements.txt file for managing dependencies. The application follows a traditional project structure with directories for images, logs, source code, temporary files, and tests. This structured approach includes installation and launch instructions, ensuring the application is easy to set up and use. Check out the video demonstrating the APP in action:</p>
	  	  <video controls>
  				<source src="{% static '/videos/imgslc.mp4' %}" type="video/mp4">
  				<p>Your browser does not support HTML5 video.</p>
  			</video>
	  	</section>
	  </article>
	<script src="{% static 'javascript/buttons.js' %}"></script>
	{% endblock content %}

templates/meteo.html
{% extends "base.html" %}
{% load static %}
<!doctype html>
<!-- templates/meteo.html -->
  <head>
	<meta charset="utf-8">
  </head>  	

	{% block content %}
	  <header>
	  	<h1 class="main">meteo</h1>
	  </header>
	  <article>
	  	<header>
	  		<h2>A Dive into GUI, Data, and Analytics</h2>
	  	</header>
	  	<nav class="basic">
	  		<a href="https://github.com/Tomas4python/meteolt_app.git" target="_blank" rel="noopener noreferrer">View code on Github</a>
	  	</nav>
	  	<section>
  			<p>As I delved deeper into the intricacies of Python coding, I felt the compelling need to acquire proficiency in GUI. From the myriad of options available, I gravitated towards tkinter primarily because it's a staple in the standard library and continues to enjoy considerable popularity.</p>
  			<p>Parallelly, I was engrossed in the acclaimed books 'Automate the Boring Stuff with Python' by Al Sweigart and 'PRACTICAL SQL: A Beginner’s Guide to Storytelling with Data' by Anthony DeBarros. Coupled with various online courses, I felt an urging desire for hands-on practice.</p>
  			<p>In my learning trajectory, I encountered a phase emphasizing databases, mathematics, and analytics. While the courses generously offered a plethora of materials, I yearned for something real and useful. I set myself the goal of measuring the accuracy of weather forecasts. Some specific task provides motivation to work and learn. This led me to the vast realm of open meteorological data.</p>
	  	</section>
	  	<section>
	  		<header>
	  			<h3>About the Application</h3>
	  		</header>
  			<p>Derived from my learning experiences, this application is designed to harness the Meteo.lt API. This API facilitates the consumption of public data from meteorological stations overseen by the Lithuanian Hydrometeorological Service, a wing under the Ministry of the Environment.</p>
				<div class="carousel_container">  
				    <div class="carousel_slide carousel2 active">
				        <a href="{% static 'images/08_forecast.jpg' %}" target="_blank">
				            <img src="{% static 'images/08_forecast_s.jpg' %}" alt="Measured and forecast view screenshot">
				        </a>
				        <figcaption>Data capturing both historical and forecast metrics.</figcaption>
				    </div>
				    <div class="carousel_slide carousel2">
				        <a href="{% static 'images/09_analysis.jpg' %}" target="_blank">
				            <img src="{% static 'images/09_analysis_s.jpg' %}" alt="Statistical table view screenshot">
				        </a>
				        <figcaption>A statistical table delineating the forecast deviations.</figcaption>
				    </div>
				    <div class="carousel_slide carousel2">
				        <a href="{% static 'images/10_graph.jpg' %}" target="_blank">
				            <img src="{% static 'images/10_graph_s.jpg' %}" alt="Console view screenshot">
				        </a>
				        <figcaption>A graphical analysis tool offering a visual representation of the data.</figcaption>
				    </div>
				    <nav class="navigation_menu">
				        <button class="carousel_button" id="prevBtn2">prev</button>
				        <button class="carousel_button" id="nextBtn2">next</button>
				    </nav>
				</div>
  			<p>One noteworthy aspect of this application's code structure is its organic evolution (without pre-design). It mirrors my step-by-step learning progression, supplemented by consistent experimentation.</p>
	  	</section>
	  	<section>
	  		<header>
	  			<h3>Key Features and Technical Details</h3>
	  		</header>
  			<ul class="no-indent">
  				<li><span class="itallic_bold_text">Modules & Structure:</span> Initially, modules were developed independently, which were eventually unified into a single, cohesive application with a unified GUI.</li>
  				<li><span class="itallic_bold_text">Learning Objectives:</span> My endeavors with this application aimed at mastering API requests, handling diverse file types (.json, .csv, .zip, .txt), and gaining prowess in various libraries.</li>
  				<li><span class="itallic_bold_text">Functionality:</span> The application can fetch both historical and current meteorological data, obtain forecast data from all accessible stations in Lithuania, and offer a comprehensive graphical analysis tool for all acquired data.</li>
  			</ul>
  			<p>In the application's second window, you'll find a table comparing absolute numbers of measured and forecasted data. Meanwhile, the third window offers a visual comparison of this data through a graph. While the table provides a broad overview, the graph highlights the temperature deviations, both positive and negative.</p>
	  	</section>
	  	<section>
	  		<header>
	  			<h4>Take a look at the video</h4>
	  		</header>
  			<p>In the video below you can better see the functionality of the application and the charm of 'tkinter' in its simplicity</p>
  			<video controls>
  				<source src="{% static '/videos/meteo.mp4' %}" type="video/mp4">
  				<p>Your browser does not support HTML5 video.</p>
  			</video>
	  	</section>
	  </article>
	<script src="{% static 'javascript/buttons.js' %}"></script>
	{% endblock content %}

templates/news.html
<!-- templates/news.html -->
{% extends "base.html" %}

{% block content %}
<h1 class="main">news</h1>
{% for post in post_list %}
 <article>
 	<h2>{{ post.title }}</h2>
	<p>{{ post.created_at|date:"j F Y, H:i" }}</p>
 	<p>{{ post.body }}</p>
 </article>
{% endfor %}
{% endblock content %}